config/routes.rb
TelefreeAgents::Application.routes.draw do
	

  resources :dashboards


  resources :call_records


  resources :addresses


  resources :calls


  resources :reports


  #resources :addresses


  resources :accounts


  #resources :calls


  resources :margins


  #resources :call_records


  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  authenticated :user do
    root :to => 'reports#index'
  end
  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  as :user do 
    root :to => "devise/sessions#new"    
    get "/login" => "devise/sessions#new"                                 
    post "/login" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy"
    get "/subscribe" => "devise/registrations#new"
    get "/reset" => "devise/passwords#new"
    put "/reset" => "devise/passwords#update"    
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end 

  resources :users
  match 'resellers' => 'users#index'
  match '*a', :to => 'errors#not_found'
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'
end

app/models/call.rb
class Call < ActiveRecord::Base
  attr_accessible :account_id, :accountcode, :amaflags, :billsec, :calldate, :callertype, :card_id, :channel, :clid, :dcontext, :did_billsec, :did_id, :did_inc_price, :did_price, :did_prov_price, :did_provider_id, :disposition, :dst, :dst_device_id, :dst_user_id, :dstchannel, :duration, :hangupcause, :lastapp, :lastdata, :localized_dst, :originator_ip, :partner_billsec, :partner_id, :partner_price, :partner_rate, :peerip, :peername, :prefix, :processed, :provider_billsec, :provider_id, :provider_price, :provider_rate, :real_billsec, :real_duration, :recvip, :reseller_billsec, :reseller_id, :reseller_price, :reseller_rate, :server_id, :sipfrom, :src, :src_device_id, :t38passthrough, :terminator_ip, :uniqueid, :uri, :user_billsec, :user_price, :user_rate, :useragent, :userfield
  belongs_to :account
end

app/controllers/calls_controller.rb
class CallsController < InheritedResources::Base
  	before_filter :authenticate_user! 
  	load_and_authorize_resource	
end

app/views/calls/_form.html.haml
= simple_form_for(@call) do |f|
  = f.error_notification

  .form-inputs
    = f.input :calldate
    = f.input :clid
    = f.input :src
    = f.input :dst
    = f.input :dcontext
    = f.input :channel
    = f.input :dstchannel
    = f.input :lastapp
    = f.input :lastdata
    = f.input :duration
    = f.input :billsec
    = f.input :disposition
    = f.input :amaflags
    = f.input :accountcode
    = f.input :uniqueid
    = f.input :userfield
    = f.input :src_device_id
    = f.input :dst_device_id
    = f.input :processed
    = f.input :did_price
    = f.input :card_id
    = f.input :provider_id
    = f.input :provider_rate
    = f.input :provider_billsec
    = f.input :provider_price
    = f.input :account_id
    = f.input :user_rate
    = f.input :user_billsec
    = f.input :user_price
    = f.input :reseller_id
    = f.input :reseller_rate
    = f.input :reseller_billsec
    = f.input :reseller_price
    = f.input :partner_id
    = f.input :partner_rate
    = f.input :partner_billsec
    = f.input :partner_price
    = f.input :prefix
    = f.input :server_id
    = f.input :hangupcause
    = f.input :callertype
    = f.input :peerip
    = f.input :recvip
    = f.input :sipfrom
    = f.input :uri
    = f.input :useragent
    = f.input :peername
    = f.input :t38passthrough
    = f.input :did_inc_price
    = f.input :did_prov_price
    = f.input :localized_dst
    = f.input :did_provider_id
    = f.input :did_id
    = f.input :originator_ip
    = f.input :terminator_ip
    = f.input :real_duration
    = f.input :real_billsec
    = f.input :did_billsec
    = f.input :dst_user_id

  .form-actions
    = f.button :submit

app/views/calls/edit.html.haml
%h1 Editing call

= render 'form'

= link_to 'Show', @call
\|
= link_to 'Back', calls_path

app/views/calls/index.html.haml
%h1 Listing calls

%table
  %tr
    %th Calldate
    %th Clid
    %th Src
    %th Dst
    %th Dcontext
    %th Channel
    %th Dstchannel
    %th Lastapp
    %th Lastdata
    %th Duration
    %th Billsec
    %th Disposition
    %th Amaflags
    %th Accountcode
    %th Uniqueid
    %th Userfield
    %th Src device
    %th Dst device
    %th Processed
    %th Did price
    %th Card
    %th Provider
    %th Provider rate
    %th Provider billsec
    %th Provider price
    %th Account
    %th User rate
    %th User billsec
    %th User price
    %th Reseller
    %th Reseller rate
    %th Reseller billsec
    %th Reseller price
    %th Partner
    %th Partner rate
    %th Partner billsec
    %th Partner price
    %th Prefix
    %th Server
    %th Hangupcause
    %th Callertype
    %th Peerip
    %th Recvip
    %th Sipfrom
    %th Uri
    %th Useragent
    %th Peername
    %th T38passthrough
    %th Did inc price
    %th Did prov price
    %th Localized dst
    %th Did provider
    %th Did
    %th Originator ip
    %th Terminator ip
    %th Real duration
    %th Real billsec
    %th Did billsec
    %th Dst user
    %th
    %th
    %th

  - @calls.each do |call|
    %tr
      %td= call.calldate
      %td= call.clid
      %td= call.src
      %td= call.dst
      %td= call.dcontext
      %td= call.channel
      %td= call.dstchannel
      %td= call.lastapp
      %td= call.lastdata
      %td= call.duration
      %td= call.billsec
      %td= call.disposition
      %td= call.amaflags
      %td= call.accountcode
      %td= call.uniqueid
      %td= call.userfield
      %td= call.src_device_id
      %td= call.dst_device_id
      %td= call.processed
      %td= call.did_price
      %td= call.card_id
      %td= call.provider_id
      %td= call.provider_rate
      %td= call.provider_billsec
      %td= call.provider_price
      %td= call.account_id
      %td= call.user_rate
      %td= call.user_billsec
      %td= call.user_price
      %td= call.reseller_id
      %td= call.reseller_rate
      %td= call.reseller_billsec
      %td= call.reseller_price
      %td= call.partner_id
      %td= call.partner_rate
      %td= call.partner_billsec
      %td= call.partner_price
      %td= call.prefix
      %td= call.server_id
      %td= call.hangupcause
      %td= call.callertype
      %td= call.peerip
      %td= call.recvip
      %td= call.sipfrom
      %td= call.uri
      %td= call.useragent
      %td= call.peername
      %td= call.t38passthrough
      %td= call.did_inc_price
      %td= call.did_prov_price
      %td= call.localized_dst
      %td= call.did_provider_id
      %td= call.did_id
      %td= call.originator_ip
      %td= call.terminator_ip
      %td= call.real_duration
      %td= call.real_billsec
      %td= call.did_billsec
      %td= call.dst_user_id
      %td= link_to 'Show', call
      %td= link_to 'Edit', edit_call_path(call)
      %td= link_to 'Destroy', call, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Call', new_call_path

app/views/calls/new.html.haml
%h1 New call

= render 'form'

= link_to 'Back', calls_path

app/views/calls/show.html.haml
%p#notice= notice

%p
  %b Calldate:
  = @call.calldate
%p
  %b Clid:
  = @call.clid
%p
  %b Src:
  = @call.src
%p
  %b Dst:
  = @call.dst
%p
  %b Dcontext:
  = @call.dcontext
%p
  %b Channel:
  = @call.channel
%p
  %b Dstchannel:
  = @call.dstchannel
%p
  %b Lastapp:
  = @call.lastapp
%p
  %b Lastdata:
  = @call.lastdata
%p
  %b Duration:
  = @call.duration
%p
  %b Billsec:
  = @call.billsec
%p
  %b Disposition:
  = @call.disposition
%p
  %b Amaflags:
  = @call.amaflags
%p
  %b Accountcode:
  = @call.accountcode
%p
  %b Uniqueid:
  = @call.uniqueid
%p
  %b Userfield:
  = @call.userfield
%p
  %b Src device:
  = @call.src_device_id
%p
  %b Dst device:
  = @call.dst_device_id
%p
  %b Processed:
  = @call.processed
%p
  %b Did price:
  = @call.did_price
%p
  %b Card:
  = @call.card_id
%p
  %b Provider:
  = @call.provider_id
%p
  %b Provider rate:
  = @call.provider_rate
%p
  %b Provider billsec:
  = @call.provider_billsec
%p
  %b Provider price:
  = @call.provider_price
%p
  %b Account:
  = @call.account_id
%p
  %b User rate:
  = @call.user_rate
%p
  %b User billsec:
  = @call.user_billsec
%p
  %b User price:
  = @call.user_price
%p
  %b Reseller:
  = @call.reseller_id
%p
  %b Reseller rate:
  = @call.reseller_rate
%p
  %b Reseller billsec:
  = @call.reseller_billsec
%p
  %b Reseller price:
  = @call.reseller_price
%p
  %b Partner:
  = @call.partner_id
%p
  %b Partner rate:
  = @call.partner_rate
%p
  %b Partner billsec:
  = @call.partner_billsec
%p
  %b Partner price:
  = @call.partner_price
%p
  %b Prefix:
  = @call.prefix
%p
  %b Server:
  = @call.server_id
%p
  %b Hangupcause:
  = @call.hangupcause
%p
  %b Callertype:
  = @call.callertype
%p
  %b Peerip:
  = @call.peerip
%p
  %b Recvip:
  = @call.recvip
%p
  %b Sipfrom:
  = @call.sipfrom
%p
  %b Uri:
  = @call.uri
%p
  %b Useragent:
  = @call.useragent
%p
  %b Peername:
  = @call.peername
%p
  %b T38passthrough:
  = @call.t38passthrough
%p
  %b Did inc price:
  = @call.did_inc_price
%p
  %b Did prov price:
  = @call.did_prov_price
%p
  %b Localized dst:
  = @call.localized_dst
%p
  %b Did provider:
  = @call.did_provider_id
%p
  %b Did:
  = @call.did_id
%p
  %b Originator ip:
  = @call.originator_ip
%p
  %b Terminator ip:
  = @call.terminator_ip
%p
  %b Real duration:
  = @call.real_duration
%p
  %b Real billsec:
  = @call.real_billsec
%p
  %b Did billsec:
  = @call.did_billsec
%p
  %b Dst user:
  = @call.dst_user_id

= link_to 'Edit', edit_call_path(@call)
\|
= link_to 'Back', calls_path