config/routes.rb
TelefreeAgents::Application.routes.draw do
	

  resources :dashboards


  resources :call_records


  resources :addresses


  resources :calls


  resources :reports


  #resources :addresses


  resources :accounts


  #resources :calls


  resources :margins


  #resources :call_records


  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  authenticated :user do
    root :to => 'reports#index'
  end
  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  as :user do 
    root :to => "devise/sessions#new"    
    get "/login" => "devise/sessions#new"                                 
    post "/login" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy"
    get "/subscribe" => "devise/registrations#new"
    get "/reset" => "devise/passwords#new"
    put "/reset" => "devise/passwords#update"    
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end 

  resources :users
  match 'resellers' => 'users#index'
  match '*a', :to => 'errors#not_found'
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'
end

app/models/user.rb
class User < ActiveRecord::Base            
	# ----------------------------------------------------------------------
	resourcify
	rolify
	belongs_to :role
	belongs_to :address
	has_many :reports, :primary_key => :accounting_code, :foreign_key => :accounting_code
	accepts_nested_attributes_for :address, :allow_destroy => true	
	devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :trackable, :validatable
	# ---------------------------------------------------------------------- 
        validates :name, :email, :accounting_code, :margin, :presence => true	
	validates :accounting_code, :numericality => { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 999, :message => 'Accounting Code must be 3 digits!'}
	validates :margin, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100, :message => 'Margin is a % between 1 and 100!'} 
	validates :email, :format => { :with => /^([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})?$/, :message => 'Email must be valid!' }
	validates_uniqueness_of :accounting_code, :message => 'Accounting Code must be unique!'
	validates_uniqueness_of :email, :message => 'A User with that email already exists!'
	# ----------------------------------------------------------------------
	before_create :set_default_role	                              
	attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :margin, :accounting_code, :created_at, :updated_at, :address_attributes, :address_id   
	# ----------------------------------------------------------------------
  	default_values  :email => { :value => lambda { Faker::Internet.email}, :allows_nil => false },
  			:accounting_code => { :value => lambda { (sprintf '%03d', rand(30..995))}, :allows_nil => false },
  			:name => { :value => lambda { Faker::Name.name}, :allows_nil => false },
  			:margin => { :value => lambda { rand(1..99) }, :allows_nil => false }  
	# ----------------------------------------------------------------------
  	def set_default_role                              
  	   self.add_role Role.find_by_name('agent')
  	end
        # ----------------------------------------------------------------------
	def role?(role_sym)                                                     
	  roles.any? { |r| r.name.underscore.to_sym == role_sym }
	end      
	# ----------------------------------------------------------------------
	# no password is required when the account is created; validate password when the user sets one
	# ----------------------------------------------------------------------
	validates_confirmation_of :password                                     
	def password_required?                                                  
	  if !persisted?                                                        
	    !(password != "")                                                   
	  else                                                                  
	    !password.nil? || !password_confirmation.nil?                       
	  end                                                                   
	end                                                                     
	# ----------------------------------------------------------------------
	# Send reset password instructions                                      
	# ----------------------------------------------------------------------
	def send_reset_password_instructions                                    
	  if self.confirmed?                                                    
	    super                                                               
	  else                                                                  
	    errors.add :base, "You must receive an invitation before you set your password."
	  end
	end  
	# ----------------------------------------------------------------------
	# override Devise method: no password confirmation required             
	# ----------------------------------------------------------------------
	def confirmation_required?                                              
	  false                                                                 
	end                                                                     
	# ----------------------------------------------------------------------
	# override Devise method: can auth only if confirmed or confirmation period has not expired
	# ----------------------------------------------------------------------
	def active_for_authentication?                                          
	  confirmed? || confirmation_period_valid?                              
	end                                                                     
	# ----------------------------------------------------------------------
	# new function to set the password                                      
	# ----------------------------------------------------------------------
	def attempt_set_password(params)                                        
	  p = {}                                                                
	  p[:password] = params[:password]                                      
	  p[:password_confirmation] = params[:password_confirmation]            
	  update_attributes(p)                                                  
	end                                                                     
	# ----------------------------------------------------------------------
	# new function to determine whether a password has been set             
	# ----------------------------------------------------------------------
	def has_no_password?                                                    
	  self.encrypted_password.blank?                                        
	end                                                                     
	# ----------------------------------------------------------------------
	# new function to provide access to protected method pending_any_confirmation
	# ----------------------------------------------------------------------
	def only_if_unconfirmed                                                 
	  pending_any_confirmation {yield}                                      
	end                                                                     
	# ----------------------------------------------------------------------
	# ----------------------------------------------------------------------
	private                                                                 
	# ----------------------------------------------------------------------
	def send_welcome_email                                                  
	  unless self.email.include?(ENV['ADMIN_EMAIL'])    
	    UserMailer.welcome_email(self.email).deliver                        
	  end 	                                                                
	end                                                                     
	# ----------------------------------------------------------------------
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  	# **********************************************************************
  	before_filter :authenticate_user! 
  	load_and_authorize_resource        
        respond_to :html, :json, :js
  	# **********************************************************************
  	def index
  	  @user = User.new
  	  @user.build_address
  	  respond_with do |format|
  	    format.json { render json: UsersDatatable.new(view_context) }   
  	  end
  	end                                                             
  	# ----------------------------------------------------------------------
  	def update    
  	  @user = User.find(params[:id])  
  	  @user.update_attributes(params[:user])     
  	  flash[:notice] = "Reseller was successfully updated." if @user.save
  	  respond_with @user
  	end   
  	# ----------------------------------------------------------------------
  	def destroy   
  	  @user = User.find(params[:id])
  	  respond_to do |format|
  	    if @user.destroy
  	      flash[:notice] = "Reseller was successfully deleted."
  	      format.js {}
  	      format.json { render json: UsersDatatable.new(view_context) }
  	    else
  	      format.html { render action: "index" }
  	      format.json { render json: @user.errors, status: :unprocessable_entity }
  	    end
  	  end    
  	end                                                                     
  	# ----------------------------------------------------------------------
end

app/views/users/_form.html.haml
= form_for @user, remote: true, url: registration_path(@user), html: {class: 'form-horizontal'} do |f|
  %table.table.simpleTable#tbl_form
    %tbody  
      %tr   
        %td(style="width:30px;")         
        %td(style="width:232px;")= f.text_field :name, :placeholder=>"Username"    
        %td(style="width:365px;")= f.email_field :email, :placeholder=>"Email" 
        %td(style="width:80px;")= f.number_field :accounting_code       
        
        %td(style="width:80px;")
          .input-append
            = f.number_field :margin
            %span.add-on %
        %td
        
      
      
      
      
      = f.fields_for :address do |a|
        %tr
          %td       
          %td= a.text_field :address_vat, :placeholder => "VAT"    
          %td= a.text_field :address_line_1, :placeholder => "Address"
          %td
          %td
          %td
        
             
        %tr
          %td
          %td= a.text_field :address_phone_1, :placeholder => "Phone" 
          %td= a.country_select :address_country, [ "Italy", "United Kingdom" ], :required => true
          %td
          %td
          %td
          
      
        %tr
          %td
          %td= a.text_field :address_fax, :placeholder => "Fax"    
          %td
          %td 
          %td
      
          
          %td         
            = button_tag :type => 'submit', :class => "pull-right btn btn-limekiln-3" do
              %i.font-awesome.icon-plus  

      
        
                  

app/views/users/_modal.html.haml
- @users.each do |user|   
  .modal.hide.fade(id = "user_#{ user.id }")  
    .modal-header
      %button.close(type="button" data-dismiss="modal" aria-hidden="true") &times;
      %h3 
        About to delete Agent
        = user.name
        
    
    .modal-body
      %p 
        .label.label-important Attention!
        Please confirm you want to remove Agent
        = user.name
    
    .modal-footer
      = link_to "Delete", user, :method => :delete, :remote => 'true', :class => "pull-right btn btn-hem-5", :data => { "loading-text" => "Deleting..."}
        

app/views/users/_user.html.haml
.modal.hide.fade(id = "user_#{ @user.id }")  
  .modal-header
    %button.close(type="button" data-dismiss="modal" aria-hidden="true") &times;
    %h3 
      About to delete Agent
      = @user.name
      
  
  .modal-body
    %p 
      .label.label-important Attention!
      Please confirm you want to remove Agent
      = @user.name
  
  .modal-footer
    = link_to "Delete", @user, :method => :delete, :remote => 'true', :class => "pull-right btn btn-hem-5", :data => { "loading-text" => "Deleting..."}

app/views/users/destroy.js.erb
$('.modal').modal('hide')
$('#tbl_users').dataTable().fnDraw();
$('#row_counter').html($('#tbl_users').dataTable().fnSettings().fnRecordsTotal())





app/views/users/index.html.haml
- content_for(:javascript) do
  = javascript_include_tag params[:controller]
/ ------------------------------------------------------------------------------     
.span4
  %h1
    %span.badge.badge-info#row_counter
    Resellers
/ ------------------------------------------------------------------------------                                 
.span12                          
  .box   
    .box-content      
      / ------------------------------------------------------------------------
      %table.table(id = "tbl_#{params[:controller]}" style="table-layout: fixed")
        / ----------------------------------------------------------------------
        %thead
          %tr
            %th(style="width:30px;")          
            %th(style="width:155px;") Name
            %th(style="width:235px;") Email
            / %th Role
            %th(style="width:80px;") Code
            %th(style="width:80px;") Margin
            %th(style="width:60px;")
            /%th Sign-in Count 
            /%th Last Sign-in 
        / ----------------------------------------------------------------------
        %tbody
      / ------------------------------------------------------------------------
      = render 'form' 

       
= render 'modal'                  