config/routes.rb
TelefreeAgents::Application.routes.draw do
	

  resources :dashboards


  resources :call_records


  resources :addresses


  resources :calls


  resources :reports


  #resources :addresses


  resources :accounts


  #resources :calls


  resources :margins


  #resources :call_records


  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  authenticated :user do
    root :to => 'reports#index'
  end
  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  as :user do 
    root :to => "devise/sessions#new"    
    get "/login" => "devise/sessions#new"                                 
    post "/login" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy"
    get "/subscribe" => "devise/registrations#new"
    get "/reset" => "devise/passwords#new"
    put "/reset" => "devise/passwords#update"    
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end 

  resources :users
  match 'resellers' => 'users#index'
  match '*a', :to => 'errors#not_found'
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'
end

app/controllers/addresses_controller.rb
class AddressesController < InheritedResources::Base
  	before_filter :authenticate_user! 
  	load_and_authorize_resource
  	respond_to :html, :json, :js
  	# **********************************************************************
  	def index
  	  respond_with do |format|
  	    format.json { render json: AddressesDatatable.new(view_context) }   
  	  end
  	end                                                             
  	# ----------------------------------------------------------------------
  	def update    
  	  @address = Address.find(params[:id])  
  	  @address.update_attributes(params[:address])     
  	  flash[:notice] = "Address was successfully updated." if @address.save
  	  respond_with @address
  	end  	
end

app/views/addresses/_form.html.haml
= simple_form_for(@address) do |f|
  = f.error_notification

  .form-inputs
    = f.input :address_country
    = f.input :address_line_1
    = f.input :address_line_2
    = f.input :address_vat
    = f.input :address_phone_1
    = f.input :address_phone_2
    = f.input :address_fax

  .form-actions
    = f.button :submit

app/views/addresses/edit.html.haml
%h1 Editing address

= render 'form'

= link_to 'Show', @address
\|
= link_to 'Back', addresses_path

app/views/addresses/index.html.haml
- content_for(:javascript) do
  = javascript_include_tag params[:controller]    
/ ------------------------------------------------------------------------------     
.span6
  %h1
    %span.badge.badge-info#row_counter
    #{params[:controller].titleize}                                               
  
/ ------------------------------------------------------------------------------                                 
.span12  
  .box   
    .box-content 
      
      / ------------------------------------------------------------------------
      %table.table(id = "tbl_#{params[:controller]}" style="table-layout: fixed")
        / ----------------------------------------------------------------------
        %thead
          %tr
            %th Reseller
            %th Country
            %th Address
            //%th Address Line 2
            %th VAT
            %th Phone
            //%th Phone 2
            %th Fax
        / ----------------------------------------------------------------------
        %tbody
      / ------------------------------------------------------------------------        

app/views/addresses/new.html.haml
%h1 New address

= render 'form'

= link_to 'Back', addresses_path

app/views/addresses/show.html.haml
%p#notice= notice

%p
  %b Address country:
  = @address.address_country
%p
  %b Address line 1:
  = @address.address_line_1
%p
  %b Address line 2:
  = @address.address_line_2
%p
  %b Address vat:
  = @address.address_vat
%p
  %b Address phone 1:
  = @address.address_phone_1
%p
  %b Address phone 2:
  = @address.address_phone_2
%p
  %b Address fax:
  = @address.address_fax

= link_to 'Edit', edit_address_path(@address)
\|
= link_to 'Back', addresses_path