config/routes.rb
TelefreeAgents::Application.routes.draw do
	

  resources :dashboards


  resources :call_records


  resources :addresses


  resources :calls


  resources :reports


  #resources :addresses


  resources :accounts


  #resources :calls


  resources :margins


  #resources :call_records


  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  authenticated :user do
    root :to => 'reports#index'
  end
  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  as :user do 
    root :to => "devise/sessions#new"    
    get "/login" => "devise/sessions#new"                                 
    post "/login" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy"
    get "/subscribe" => "devise/registrations#new"
    get "/reset" => "devise/passwords#new"
    put "/reset" => "devise/passwords#update"    
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end 

  resources :users
  match 'resellers' => 'users#index'
  match '*a', :to => 'errors#not_found'
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/dashboards_controller.rb
class DashboardsController < InheritedResources::Base
  	before_filter :authenticate_user! 
  	load_and_authorize_resource        
        respond_to :html, :json, :js, :xls, :only => :index
        
  	# **********************************************************************
  	#                                                                
  	# **********************************************************************
  	def index     
  	  if (current_user.has_role? :admin or current_user.has_role? :owner)  
  	     @resellers = User.all
  	     @reports = Report.all.group_by(&:user_name)
          else   
             @resellers = current_user
             @reports = Report.where(accounting_code: current_user.accounting_code).group_by(&:user_name)
          end   		
          @response = {:resellers => @resellers, :reports => @reports}
	  respond_with @response  
  	  
  	end 		
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_form.html.haml
= simple_form_for(@dashboard) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/dashboards/edit.html.haml
%h1 Editing dashboard

= render 'form'

= link_to 'Show', @dashboard
\|
= link_to 'Back', dashboards_path

app/views/dashboards/index.html.haml
- content_for(:javascript) do
  = javascript_include_tag params[:controller]
#acc_code(style="display:none;") 
  = current_user.accounting_code    
- if (current_user.has_role? :admin or current_user.has_role? :owner)  
  #can_view(style="display:none;")= "all"   

/ ------------------------------------------------------------------------------     
.span6
  %h1
    %span.badge.badge-info#row_counter= @response[:reports].count.to_s
    //#{params[:controller].singularize.titleize}
    Margins
  %p
    Aggregate total margin for each customer. Values are updated every hour.
    
.span12
  //= javascript_include_tag "http://www.google.com/jsapi", "chartkick"
  //= line_chart Report.where(accounting_code: current_user.accounting_code).group_by_day(:updated_at).group_by(&:user_name).sum(:margin)
  .box    
    .box-content
                       
      %form.pull-left
        %input#filter_tbl(placeholder="Search by Customer or Reseller")

      / ------------------------------------------------------------------------
      %table.table(id = "tbl_#{params[:controller]}")
        / ----------------------------------------------------------------------
        %thead
          %tr
            - if (current_user.has_role? :admin or current_user.has_role? :owner)
              %th Reseller 
            %th Customer
            %th Calls
            %th Minutes
            %th Price
            - if (current_user.has_role? :admin or current_user.has_role? :owner)
              %th Margin             
        / ----------------------------------------------------------------------
        %tbody	
          - @response[:reports].each do |key,value|
            %tr
              - if (current_user.has_role? :admin or current_user.has_role? :owner)
                %td= User.where(accounting_code: value.map(&:accounting_code)[0]).first.name
                
              %td= key      
              %td= value.sum(&:call_count)
              %td= value.sum(&:duration_sec)
              %td= value.sum(&:price).round(2)
              - if (current_user.has_role? :admin or current_user.has_role? :owner)
                %td= value.sum(&:margin).round(2)  
                
                
      :javascript              
        $('#filter_tbl').keyup(function() {
            var that = this;
            $.each($('tbody tr'),
            function(i, val) {
                if ($(val).text().indexOf($(that).val()) == -1) {
                    $('tbody tr').eq(i).hide();
                } else {
                    $('tbody tr').eq(i).show();
                }
            });
        });        
      
                
         
              

app/views/dashboards/new.html.haml
%h1 New dashboard

= render 'form'

= link_to 'Back', dashboards_path

app/views/dashboards/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_dashboard_path(@dashboard)
\|
= link_to 'Back', dashboards_path